spring:
  application:
    name: oauth2-demo

  security:
    oauth2:
      client: # Configuration for Client 1: Web App (Authorization Code Flow)
        registration:
          keycloak: 
            provider: keycloak
            client-id: demo-web-client
            client-secret: FFUCSXhGUofYrbKoDnSNsEgKYID46LrX
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/${spring.application.name}
      resourceserver:
        jwt: # Configuration for Client 2: API (Resource Server)
          issuer-uri: http://localhost:9090/realms/${spring.application.name}

keycloak: # Custom properties for Client 3: Admin API
  admin:
    server-url: http://localhost:9090
    realm: master  # Authenticate to the master realm
    target-realm: ${spring.application.name} # Manage users in our app realm
    client-id: demo-admin-client
    client-secret: 6WROqpEYBUq125U3Q1NVQAYgKVzTrIzm
    